name: Versioning and build

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: '¿Qué tipo de versión quieres incrementar?'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

env:
  GAR_LOCATION: europe-west1-docker.pkg.dev/atlantean-app-120410/sporttia/licitaciones-sync
  DEFAULT_TAG: 0.0.0.0
  COMMIT_FILTER: "^(feat|fix|docs|chore|refactor|test|style|perf|ci)(\\([^)]+\\))?:.*"

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    outputs:
      new_version: ${{ steps.get_version.outputs.new_version }}
      tag_commits: ${{ steps.get_commits.outputs.tag_commits }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make all scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Determine version type
        id: version_type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION_TYPE=${{ github.event.inputs.bump }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_HEAD_REF}" == feature/* ]] || [[ "${GITHUB_HEAD_REF}" == feat/* ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_ENV
          elif [[ "${GITHUB_HEAD_REF}" == fix/* ]] || [[ "${GITHUB_HEAD_REF}" == hotfix/* ]]; then
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
          else
            echo "::error::No valid version type detected."
            exit 1
          fi

      - name: Run versioning script
        id: get_version
        run: |
          NEW_VERSION=$(.github/scripts/get_update_version.sh "$VERSION_TYPE")
          echo "New version calculated: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Get last tag
        id: get_last_tag
        run: |
          LAST_TAG=$(.github/scripts/get_last_tag.sh "$DEFAULT_TAG")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

      - name: Get formatted commits
        id: get_commits
        run: |
          TAG_COMMITS=$(.github/scripts/get_commits.sh "$LAST_TAG" "$COMMIT_FILTER")

          if [[ -z "$TAG_COMMITS" ]]; then
            echo "::error::❌ No relevant commits found since $LAST_TAG. Exiting."
            exit 1
          fi

          echo "tag_commits<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: versioning
    env:
      NEW_VERSION: ${{ needs.versioning.outputs.new_version }}
      TAG_COMMITS: ${{ needs.versioning.outputs.tag_commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHA
        id: git_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "gitsha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "gitsha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-app
          key: ${{ runner.os }}-buildx-app-${{ steps.git_sha.outputs.gitsha }}
          restore-keys: |
            ${{ runner.os }}-buildx-app-

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.GAR_LOCATION }}:${{ env.NEW_VERSION }},${{ env.GAR_LOCATION }}:latest
          build-args: |
            NEW_VERSION=${{ env.NEW_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache-app
          cache-to: type=local,dest=/tmp/.buildx-cache-app-new,mode=max
          provenance: false

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-app
          mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app

  tagging-and-commiting:
    runs-on: ubuntu-latest
    needs: [versioning, build]
    permissions:
      contents: write
    env:
      NEW_VERSION: ${{ needs.versioning.outputs.new_version }}
      TAG_COMMITS: ${{ needs.versioning.outputs.tag_commits }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update package.json with the new version
        run: |
          echo "Updating package.json version to $NEW_VERSION"
          jq --arg version "$NEW_VERSION" '.version = $version' package.json > temp.json && mv temp.json package.json

      - name: Commit and push updated version
        run: |
          git add package.json
          git commit -m "build: update version $NEW_VERSION"
          git push origin HEAD:main

      - name: Create and push tag
        run: |
          git tag -a "$NEW_VERSION" -m "Version $NEW_VERSION" -m "$TAG_COMMITS"
          git push origin "$NEW_VERSION"

  cleanup:
    runs-on: ubuntu-latest
    needs: tagging-and-commiting
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete previous caches except the latest
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache keys"

          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | grep "${OS}-buildx-app-" | sort -r | tail -n +2 | cut -f 1)

          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          OS: ${{ runner.os }}
